# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Homepage of Yalin Liu (刘亚林)
# brief-intro: Researcher
email: ylliu@hkmu.edu.hk
# description: Yalin Liu
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

baseurl: "/homepage" # the subpath of your site, e.g. /blog
url: "https://yalin-liu.github.io" # the base hostname & protocol for your site
github_username: yalin-liu
permalink: /:year/:month/:day/:title/

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: yalin-liu
duoshuo_url: "https://github.com/yalin-liu/"
# disqus_shortname: yalin-liu

# Build settings
markdown: kramdown

port: 4001
