# Site settings
title: Homepage of Yalin Liu (刘亚林)
email: yalin_liu@foxmail.com
description: Yalin Liu
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: yalin-liu
permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/yalin-liu/yalin-academic/blob/5c18175407ea851814cd7f6d95a0a042b13068d5/
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/yalin-liu/yalin-academic.gitHub.io/
#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
# duoshuo_shortname: mengding
# duoshuo_url: "https://github.com/yangjinghua94/"
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
#disqus_shortname: pfzuo
#disqus_url: "http://pfzuo.github.io"
#########################################

# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false

port: 4001
